### ISSUE TITLE
Unable to open stub file ./stub/n2e-asm-1d00-stub

### ISSUE THREAD

**Issue by Arvinzhu** [ps2dev/ps2-packer#20]
```
root@ubuntu:~/tools/ps2-packer# ./ps2-packer ./remote-viewer  ./remote-viewer-packed
PS2-Packer v1.1.0 (C) 2004-2005 Nicolas "Pixel" Noble
This is free software with ABSOLUTELY NO WARRANTY.

Using special ucl-nrv2e asm (multiple sections) stub
Unable to open stub file ./stub/n2e-asm-1d00-stub

```

Can you tell me what  is  this file ' ./stub/n2e-asm-1d00-stub' ?

**Comment by sp193** [comment]
The full version (not lite) of ps2-packer supports multiple compression methods. Each compression method requires a packer & unpacking stub. n2e-asm-1d00-stub is an unpacking stub.

There are a two possible places for the stubs to be located in:
- /share/ps2-packer/module/*
- stub/*
