### ISSUE TITLE
Add $DESTDIR in makefile install rules

### ISSUE THREAD

**Issue by sl1pkn07** [ps2dev/ps2-packer#6]
Hi

attach the patch to add $(DESTDIR) in Makefile install section

(for helper package maintainers)

http://sl1pkn07.no-ip.com/paste/view/5196c905

greetings

**Comment by sp193** [comment]
This is old, but I have only just figured out what this is about.
Can you elaborate why you couldn't just change the PREFIX variable? If it is desirable to allow PREFIX to be changed externally, we could perhaps make it conditional:
```
PREFIX ?= $(PS2DEV)
```

**Comment by sp193** [comment]
Completed in c6e8c38.
